---
title: "The Cure to Range Anxiety"
subtitle: "Battery Lifetime Prediction with Machine Learning"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
format: 
  html:
    toc: true
    toc-depth: 3
    theme: cosmo
  pdf:
    toc: true
    toc-depth: 3
---

### [Why Should we Care about Battery Lifetime Prediction?]{.underline}

Batteries have become widely used in many industries including medical devices, automotive vehicles and energy storage systems. As part of a push for renewable energy solutions to combat climate change and the demand for better wearable and or implantable medical technologies, battery technology has accelerated in growth in recent years. Electric cars are more prevalent than ever, energy storage for renewable solar and wind energy is growing faster than ever and portable battery powered devices are sold by countless companies. The adoption of electric vehicles is divisive to say the least, and a major deterrent for people is "range anxiety". Range anxiety refers to when people alter or would alter their driving habits or trips due to fear of running out of charge in their electric vehicle battery. This can happen due to poor trip planning, or areas in countries with few electric charger stations where the potential for getting stranded is real.

For most day-to-day commuters with electric vehicles this is not a worry. However, consider additionally the cost of replacing an electric vehicle battery early. The cost could be a large proportion of the total cost of the vehicle itself, and moreover, you may have convinced yourself to buy an electric vehicle due to the savings on gas. Perhaps you finally reached your payback period on your electric car purchase providing savings on gas to offset the delta between the gas vehicle price and the electric vehicle price. All of those savings can go down the drain if your battery needs to be replaced all of the sudden after you hit your payback period... What is the solution? It is easy - let's increase the lifetime cycle of electric vehicle batteries! Oh wait... this is not a trivial task... If that is not enough motivation for why this matters, maybe I should also mention that the probability of a catastrophic failure in the battery pack potentially leading to a fire or explosion, skyrockets when a battery degrades to a state of health (SOH) where it only has 80% of its original capacity to hold charge.

Batteries are complex physical systems, which demand analysis of data and design considerations in multiple displines of engineering inlcuding mechanical, materials, electrical and chemical. It turns out, that you can model a large proportion of the the complex behaviour of the internal battery components and physics, if you can accurately estimate the battery's current and future state of charge (SOC). The SOC is a function of time and current going in or out of the battery and is measured in amp-hours (Ah). It tells us how much charge (energy per-Volt) is available in the battery to do useful work. The main issue with modelling SOC over time is the fact that use of the battery affects the mechanics of SOC. A major issue with battery technologies is the decrease in SOC overtime due to use. This phenomenon is referred to as battery ageing, and the amount of complexity and interdependent mechanisms at play make it very difficult to estimate with standard physics equation paradigms. Predicting in a quantitative way when this degradation will occur and by how much, turns out to be an extremely difficult problem with many variables influencing the so-called battery capacity lifetime (or commonly just referred to as battery lifetime).

### [Battery Liftime Prediciton in Era of AI]{.underline}

One of the reasons machine learning and AI are such powerful tools in modern data analysis is their wide range of applicability to real-world problems across many different fields. One such field with extensive ongoing research for machine learning applications is battery design and technology. The analysis of the data centered around these technologies has therefore become increasingly important in recent years as well. Machine learning and AI techniques for predicting of battery system behavior with laboratory or field data is at the frontier of development of these technologies. It turns out that with enough voltage, temperature and current data of a battery charging and discharging (simulated battery use in a laboratory or collected in the field during use), these predictions become tractable with physics modelling frameworks and machine learning techniques.

Here is an example of real-world drive-cycle data for an electric vehicle, which could be used in a training datset for a machine learning model describing power consumption and regeneration. Note that voltage, temperature and current data would also be logged during this test. We can see that drive-cycle consumption patterns, and therefore SOC variation changes with the category of road type as well.

![Deep Dive Analysis 1: Drive Cycle Assessment \[5\]](img/Fig5.png){#fig-fig5}

@fig-fig5 shows us the power consumption/regeneration in kW. When the vehicle is braking regeneratively the battery is charging and the power consumption is negative, whereas when the vehicle is holding a constant speed or accelerating power consumption is positive and the battery is discharging.

The state of the art of battery lifetime prediction models, almost always involves machine learning today \[1\]\[2\]\[3\]\[4\]. The models applied in this domain are time series in nature, and therefore the examples in the training and test data are causally linked through time dependence unlike models of other regression or classification applications. This comes with its own assumptions and challenges, however the battery lifetime prediction has become increasingly accurate and reliable consequently.

Here are some examples of what battery lifetime prediction with machine learning can tell us...

![Battery lifetime prediction across diverse ageing conditions with inter-cell deep learning \[1\]](img/Fig1.png){#fig-fig1}

@fig-fig1 shows us how the SOC percentage decrease predictions change with charge-discharge cycling (use) for different ageing factors, relative to beginning of life (BOL) when the battery was manufactured.

A similar cycle-life plot is shown below, but for predictions for different chemistry types:

![Feature engineering for machine learning enabled early prediction of battery lifetime \[2\]](img/Fig2.jpg){#fig-fig2}

We can see from @fig-fig2 that the physics-informed feature model predicts the cycle life for different chemistries with a reasonable spread of cycles, but some chemistries are harder to predict than others.

Another approach is to use formation data to build the model for predictions. Formation is the cycling done on the battery cell during manufacturing in order to stabilize the chemistry. Typically formation cycles are not counted as cycles before BOL, since the cycles are not actual end-user field use. Additionally, SOC calculations during formation can vary widely before stabilization occurs.

![Machine learning for battery quality classification and lifetime prediction using formation data \[3\]](img/Fig3.jpg){#fig-fig3}

@fig-fig4 below also illustrates how deep learning can be used in the battery lifetime prediction machine learning pipeline with real-world driving data:

![Real Driving Cycle-Based State of Charge Prediction for EV Batteries Using Deep Learning Methods \[4\]](img/Fig4.png){#fig-fig4}

### [**Problems with the Machine Learning Approach**]{.underline}

The major problem in the field currently is the scarcity of high-quality data for training the models \[1\]. This is due to proprietary company data not being widely available and the cost of collecting the data as it requires intensive labor, capital and physical space to execute testing, in comparison with data collection for other applications. If the scarcity of data problem can be solved in the future, we will without a doubt see advances in machine learning for battery lifetime prediction. Another problem has to do with the fact that obtaining this real-word, large, high-quality training datasets has time and capital limitations on it. Evolving stable battery chemistry formulations, that are safer with a greater lifetime are constantly being researched and developed. The adoption of new chemistries will require the collection of new testing data and field use data in order for Machine Learning models to catch up with the new technology. In this sense, successful machine learning models for lifetime prediction will likely always lag behind battery chemistry innovation and this may slow the progress of the research and technological development.

### [**References**]{.underline}

1.  [Battery lifetime prediction across diverse ageing conditions with inter-cell deep learning](https://www.nature.com/articles/s42256-024-00972-x)
2.  [Feature engineering for machine learning enabled early prediction of battery lifetime](https://www.sciencedirect.com/science/article/abs/pii/S0378775322001495)
3.  [Machine learning for battery quality classification and lifetime prediction using formation data](https://www.sciencedirect.com/science/article/pii/S2666546824001174)
4.  [Real Driving Cycle-Based State of Charge Prediction for EV Batteries Using Deep Learning Methods](https://www.mdpi.com/2076-3417/11/23/11285)
5.  [Deep Dive Analysis 1: Drive Cycle Assessment](https://bett.cenex.co.uk/bett-learnings/deep-dive-report-1-drive-cycle-analysis)
